export const CLIENT_ERROR = {
  BAD_LOGIN: 'auth/bad-login',
  PERMISSION_DENIED: 'auth/permission-denied',
  GEKKO_OFFLINE: 'auth/gekko-offline',
  RESOURCE_NOT_FOUND: 'request/bad-request',
  BAD_REQUEST: 'request/bad-request',
  TO_MANY_REQUEST: 'request/tom-many-request',
  NOT_EXECUTED: 'request/not-executed',
  INTERNAL_SERVER_ERROR: 'request/internal-server-error',
  SERVICE_NOT_AVAILABLE: 'request/service-not-available',
  SYSTEM_NOT_INITIALIZED: 'client/system-not-initialized',
  ALREADY_INITIALIZED: 'client/already-initialized',
  SYSTEM_NOT_ENABLED: 'client/system-not-enabled',
  CANNOT_PARSE_STATUS: 'client-cannot-parse-status',
};
