name: Publish Package to npmjs

on:
  release:
    types: [published]

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn build

      - name: Publish to npm
        run: npm stage publish
